(load (merge-pathnames "wizard_fns.lisp" *load-truename*))
(load (merge-pathnames "wizard_consts.lisp" *load-truename*))
(load (merge-pathnames "wizard_init_state.lisp" *load-truename*))
(load (merge-pathnames "wizard_commands.lisp" *load-truename*))
(load (merge-pathnames "wizard_repl.lisp" *load-truename*))
